### ISSUE TITLE
major bug

### ISSUE THREAD

**Issue by yexu78** [azerothcore/mod-solocraft#18]
Dungeons to dungeons, unlimited upgrade attributes

**Comment by LannyE** [comment]
Can you write down the steps you did to reproduce the problem?  I am pretty sure I have a one line of code solution for this but I want to test it.

**Comment by D3thw0lf** [comment]
You can boost the already boosted stats by moving from one dungeon to another (e.g. Dungeonfinder).

You can easily test that by going into Blackrock Depths and from there (in that Dungeon) into Molten Core (via Portal in Dungeon)

**Comment by LannyE** [comment]
This issue should be closed with merging of #19.

**Comment by Helias** [comment]
ok, I am closing this so, if the bug still persist feel free to reopen this issue

**Comment by Valoriaz** [comment]
I need to reopen .. the stats stacking exist always..and with the PR i cant compile the Server..the worldserver give me this error :
unexpected mysql errno 1264. Unexpected Behavior possible

**Comment by Valoriaz** [comment]
For additional information

I already had Solocraft on my server.. it also worked.. but from today to tomorrow.. only newly created characters have the problem.. existing characters scale wonderfully and without errors when going in and out of the instance. With newly created characters, this error comes up: unexpected mysql errno 1264. Unexpected Behavior possible

**Comment by Valoriaz** [comment]
found my own solution 
https://github.com/azerothcore/mod-solocraft/pull/31 
maybe this help
