### ISSUE TITLE
Scaling of agility leads to superiority of Rogue, Hunter, Druid and especially Shamans.

### ISSUE THREAD

**Issue by TenebrisWoW** [azerothcore/mod-solocraft#27]
By scaling agility, the corresponding classes get such a high dodge rating that they are hardly hit and tank-classes with strength that are fully skilled and equipped easily beat. In addition, they do immensely more damage than these classes. It would be optimal to scale attack power instead of agility.

It is already great that you can change the overall scaling for the individual classes. Scaling the individual values would be natural even better and a way to influence this problem.

**Comment by pangolp** [comment]
Good afternoon, currently I don't know if you are still using the emulator and the module, but for now, to try to clean up the repository and receive current reports, I'm going to close this topic. In case, that you are still using the module, and the error that you describe, still occurs, I ask you to open a problem again and we try to find a solution to the problem, in case they really start. Thank you.
