### ISSUE TITLE
The mod-dynamic-xp module has no experience bonus in the copy after setting the experience balance

### ISSUE THREAD

**Issue by adink1** [azerothcore/mod-solocraft#30]
After setting the experience balance, the mod-dynamic-xp module has no experience bonus in the copy, all experience is forced to be compressed to the default value

**Comment by pangolp** [comment]
Good afternoon, currently I don't know if you are still using the emulator and the module, but for now, to try to clean up the repository and receive current reports, I'm going to close this topic. In case, that you are still using the module, and the error that you describe, still occurs, I ask you to open a problem again and we try to find a solution to the problem, in case they really start. Thank you.
