### ISSUE TITLE
Vehicles do not receive any scaling

### ISSUE THREAD

**Issue by entropiccode** [azerothcore/mod-solocraft#33]
Any vehicles players enter during dungeons or raids are not scaled accordingly with the player.  This is a problem for raids such as Eye of Eternity (Malygos forces all players onto Drakes) and Ulduar (entrance section is in vehicles).

Vehicles should receive the same scaling as the player driving them.

**Comment by pangolp** [comment]
Good afternoon, currently I don't know if you are still using the emulator and the module, but for now, to try to clean up the repository and receive current reports, I'm going to close this topic. In case, that you are still using the module, and the error that you describe, still occurs, I ask you to open a problem again and we try to find a solution to the problem, in case they really start. Thank you.
