### ISSUE TITLE
EXP sink down to x0,1 Rate

### ISSUE THREAD

**Issue by MaDmaX1337** [azerothcore/mod-solocraft#34]
I don't know how but it happen.

My Server run now 1,5 hours and the EXP dropped down to 6 exp per kill with level 1.

My rate is x6.

Rate.XP.Kill      = 6

I have no idea if it's constant or when someone using Instances.

Hint: I have a bunch of Modules running but all with exp is the Solocraft and Weekend EXP Module. So far i tested, its Solocraft which causing this.

Rev.
![image](https://user-images.githubusercontent.com/11060723/193838280-0c6b73fb-dd2f-4e49-815a-d786e2f0b3bd.png)

**Comment by pangolp** [comment]
Good afternoon, currently I don't know if you are still using the emulator and the module, but for now, to try to clean up the repository and receive current reports, I'm going to close this topic. In case, that you are still using the module, and the error that you describe, still occurs, I ask you to open a problem again and we try to find a solution to the problem, in case they really start. Thank you.
