### ISSUE TITLE
Bug: XP Rate Issue w/ Mob Kills

### ISSUE THREAD

**Issue by spiffynacho** [azerothcore/mod-solocraft#42]
### Current Behaviour

Without ever being in a dungeon and while playing solo, server players are mentioning XP rates are way off.  Just killing normal mobs out of dungeons are yielding significantly lower XP rates than normal.  Disabling mod fixes the issue.  I am using the stock configuration for the mod.

### Expected Behaviour

XP Rates should be unaffected and remain the same

### Steps to reproduce the problem

1. Kill a monster outside of a dungeon.  This issue seems to be happening more frequently with orange monsters.  Yellow and Green monsters are yielding the correct XP, but higher level monsters are much lower XP.

### AC rev. hash/commit

AzerothCore rev. eb1ecc38a5a3 2023-12-02 21:13:20 +0100 (master branch) (Win64, RelWithDebInfo, Static)
Connected players: 4. Characters in world: 4.
Connection peak: 5.
Server uptime: 12 minute(s) 18 second(s)
Update time diff: 1ms, average: 8ms.
Using SSL version: OpenSSL 3.0.11 19 Sep 2023 (library: OpenSSL 3.0.11 19 Sep 2023)
Using Boost version: 1.81.0
Using CMake version: 3.27.7
Using MySQL version: 80034
Found MySQL Executable: C:/Program Files/MySQL/MySQL Server 8.0/bin/mysql.exe
Compiled on: Windows 10.0.20348
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in C:/Build/bin/RelWithDebInfo/Data/maps. Total size: 291014951 bytes
vmaps directory located in C:/Build/bin/RelWithDebInfo/Data/vmaps. Total size: 658130721 bytes
mmaps directory located in C:/Build/bin/RelWithDebInfo/Data/mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.10-dev
Latest LoginDatabase update: 2023_04_24_00.sql
Latest CharacterDatabase update: mod_solo_craft.sql
Latest WorldDatabase update: 2023_12_02_00.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- BreakingNewsOverride
- mod-solo-lfg
- mod-solocraft
- mod-weekendbonus

### Operating system

Windows Server 2022 Standard

### Custom changes or Modules

- BreakingNewsOverride
- mod-solo-lfg (disabled)
- mod-solocraft (disabled)
- mod-weekendbonus
- All professions enabled in worldserver configuration

**Comment by pangolp** [comment]
At first glance, from what I see in the code, it seems so, because at no time, to apply the multiplier, is it taken into account whether or not the player is within an instance. Anyway, I would have to test it. Is the idea of the module only to adjust the difficulty within the dungeons and raids or also in the open world? Because if the answer is the second, that's fine then, now, if it only has to be in dungeons and raids, an adjustment needs to be made.

**Comment by Hotschmoe** [comment]
PR to fix it here. working for us

https://github.com/azerothcore/mod-solocraft/pull/49#issue-2477343732
