### ISSUE TITLE
Bug: XP modifiers are global - players not in group affected also

### ISSUE THREAD

**Issue by squeakyneb** [azerothcore/mod-solocraft#46]
### Current Behaviour

If one group of players enter an instance that triggers XP modifiers, everyone online is affected.

### Expected Behaviour

Only the group in the raid is affected by the XP modifier.

### Steps to reproduce the problem

1. Get two friends to party up and enter a raid (Molten Core for example)
2. Play a character somewhere else, not in the group (e.g. start a new character)
3. Observe that XP is severely debuffed (hand in the first quest and get nowhere near level 2)

### Extra Notes

I know it's called SOLOcraft, but the description said "Adjusts player stats for raids based on the # of players in the group" so it sounded like it's also fit for larger playerbases.

### AC rev. hash/commit

 AzerothCore rev. 8cfb3383287b+ 2024-07-31 09:10:12 +0200 (master branch) (Unix, RelWithDebInfo, Static)

### Operating system

Rocky Linux 8

### Custom changes or Modules

List of enabled modules:
|- BreakingNewsOverride
|- DungeonRespawn
|- StatBooster
|- mod-ah-bot
|- mod-individual-xp
|- mod-no-hearthstone-cooldown
|- mod-npc-enchanter
|- mod-skip-dk-starting-area
|- mod-solo-lfg
|- mod-solocraft

**Comment by Hotschmoe** [comment]
PR in to fix it here, working for us

https://github.com/azerothcore/mod-solocraft/pull/49#issue-2477343732
