### ISSUE TITLE
some considerations

### ISSUE THREAD

**Issue by Yehonal** [azerothcore/mod-solocraft#5]
I've developed this module years ago allowing any instance to scale up with any party dimension and level: https://github.com/azerothcore/mod-autobalance

Is there something that mod-solocraft does better? if yes we can merge that feature in autobalance since i think mod-autobalance is more complete.

**Comment by BarbzYHOOL** [comment]
yes, I don't know but you are totally right

Need someone who uses it to give his opinion. @milestorme do you use both?

**Comment by milestorme** [comment]
I only use vas

**Comment by BarbzYHOOL** [comment]
@gtao725 do you use both?

**Comment by milestorme** [comment]
On Stygian repack he was using them together, I’m not sure why , vas pretty much covers everything , this seems to boost players and it’s a little unbalanced on some characters,  we found , 

I think a benefit of this mod over vas is this modules ability to leave dungeons and raids at their regular levels , un-scaled . Where as using mod-autobalance dungeons scale so stockades when re-run at 60 is scaled to 60

**Comment by BarbzYHOOL** [comment]
Well so it means it's two different ways so it should not be deleted.

**Comment by gtao725** [comment]
Yes I use both but I never turn on both at the same time.

**Comment by Yehonal** [comment]
Well since they are two different modules (mod-solocraft boost the player instead autobalance acts on creatures)

we can close it :)
